# Increase memory for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Use official Kotlin code style
kotlin.code.style=official

# Parallel execution and caching for faster builds
# org.gradle.parallel=true
# org.gradle.caching=true
android.suppressUnsupportedCompileSdk=36
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=false
